### ISSUE TITLE
decal worker fails with " ImportError: cannot import name 'write_ds9' from 'regions' "

### ISSUE THREAD

**Issue by a-benati** [caracal-pipeline/caracal#1581]
Hello,

the ddcal worker fails when importing `write_ds9` from `regions`. I checked the code and it says that the relative line should be rewritten since write_ds9 does not exist anymore (line 273 of ddcal_worker.py). Has anyone solved this already?

Thanks,
Alessandro Benati

**Comment by Athanaseus** [comment]
Hi  @a-benati,

Thanks for opening the issue.
Currently, this is resolved by pinning the version of `regions==0.7`.
It should be the case if you are running with the latest `caracal` release version or even master installed using the `poetry.lock` file.
Please confirm the version of `caracal` and the installation steps used.

Best regards

**Comment by a-benati** [comment]
Hi,

thanks for your answer. I am working with caracal version 1.1.3 and I have installed it through singularity. The output of the command `pip freeze | grep regions` is: `regions==0.7`, which I think it means that I already have that version of `regions`.

**Comment by Athanaseus** [comment]
Yes, that's right. Sorry, this was meant to be `regions==0.5`.
Try the above. In the meantime, I'll push a fix with the latest `regions`, and you can test it also.

**Comment by Athanaseus** [comment]
@a-benati please checkout `update_regions` branch or `pip install git+https://github.com/caracal-pipeline/caracal.git@update_regions`
